name: Create Nuget Packages
description: Creates a Nuget packages from compiled sources

branding:
  color: blue
  icon: package

inputs:
  project-names:
    description: List of project names to pack separately.
    required: true
  package-version:
    description: Version of the Nuget packages.
    required: true
  output-dir:
    description: Directory where all packages will be put (default value is 'packages').
    required: false
    default: packages
  build-configuration:
    description: Build configuration for the build (default value is 'Release').
    required: false
    default: Release
  skip-build:
    description: Whether to skip the build using the --no-build flag (default value is 'true')
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Create Nuget packages
      shell: bash
      run: |
        if [[ '${{ inputs.package-version }}' =~ ^v(.+)$ ]] ; then
          VERSION="${BASH_REMATCH[1]}"
        else
          VERSION='${{ inputs.package-version }}'
        fi
        ARGS='-o "${{ inputs.output-dir }}" -c "${{ inputs.build-configuration }}"'
        ARGS="${ARGS} -p:Version=${VERSION}"
        if [[ '${{ inputs.skip-build }}' == "true" ]] ; then
          ARGS="${ARGS} --no-build"
        fi
        PROJECT_NAMES=`echo '${{ inputs.project-names }}'`
        for PROJECT_NAME in ${PROJECT_NAMES} ; do
          dotnet pack "${PROJECT_NAME}" ${ARGS}
        done
